version: 2

run:
  timeout: 5m
  tests: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  gocyclo:
    min-complexity: 15
  
  revive:
    confidence: 0.8
  
  govet:
    enable-all: true
  
  misspell:
    locale: US
  
  nakedret:
    max-func-lines: 30
  
  unparam:
    check-exported: false

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-dirs:
    - vendor
    - .bmad-core
    - expansion-pack
  
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - revive
    
    # Exclude unused warnings for UI view methods that are part of the interface
    - path: internal/ui/view\.go
      linters:
        - unused
    
    # Exclude unused warnings for utility functions that may be used in future
    - path: internal/ui/components/modal\.go
      linters:
        - unused
    
    # Allow hardcoded strings in UI components during development
    - path: internal/ui/
      linters:
        - revive
    
    # Allow build utilities flexibility
    - path: internal/testutil/
      linters:
        - revive
    
    # Allow main.go flexibility during development
    - path: main\.go
      linters:
        - errcheck
        - revive
    
    # Disable field alignment warnings during development
    - linters:
        - govet
      text: "fieldalignment:"
    
    # Disable additional warnings during development phase
    - linters:
        - staticcheck
      text: "SA9003:"  # empty branch
    - linters:
        - staticcheck
      text: "SA1019:"  # deprecated usage
    - linters:
        - staticcheck
      text: "SA4006:"  # unused assignment
    
    # Exclude shadow checking for common variable names
    - text: "shadow: declaration of \"err\""
      linters:
        - govet
    
    # Exclude known style issues during development
    - linters:
        - gocritic
      text: "captLocal:"  # capture loop variable
    - linters:
        - gocritic
      text: "commentedOutCode:"  # commented code

  max-issues-per-linter: 0
  max-same-issues: 0