# Official golangci-lint v2 format
version: "2"

run:
  timeout: 5m

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude:
    - "shadow: declaration of \"err\""
    - "var-naming: avoid meaningless package names"
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - funlen
  max-issues-per-linter: 0
  max-same-issues: 0