run:
  timeout: 5m
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  gocyclo:
    min-complexity: 15
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: cc-mcp-manager
  
  revive:
    confidence: 0.8
  
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    # Basic linters that don't use goanalysis
    - errcheck
    - gofmt
    - goimports
    - misspell
    - revive
    - gocyclo
    - gosimple
    - ineffassign
    # Note: Excluding govet and staticcheck temporarily due to Go 1.24 compatibility

issues:
  exclude-dirs:
    - vendor
    - .bmad-core
    - expansion-packs
  
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
    
    # Allow longer functions in UI components during development
    - path: internal/ui/
      linters:
        - goconst
    
    # Allow main.go flexibility during development
    - path: main\.go
      linters:
        - errcheck
    
    # Allow simple fmt.Sprintf usage during development
    - linters:
        - gosimple
      text: "unnecessary use of fmt.Sprintf"

  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0
  
  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0