# Official golangci-lint v2 format
version: "2"

run:
  timeout: 5m

linters:
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  funlen:
    lines: 100
    statements: 50
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  gosec:
    excludes:
      - G204 # subprocess launched with variable (acceptable in tests)
      - G301 # directory permissions (acceptable in tests)
      - G302 # file permissions (acceptable in tests)
      - G304 # file inclusion via variable (acceptable in tests)

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Exclude security checks for test files
    - path: "_test\\.go"
      linters:
        - gosec
    # Exclude function length checks for test files
    - path: "_test\\.go"
      linters:
        - funlen
    # Exclude duplicate code checks for test files (common test patterns)
    - path: "_test\\.go"
      linters:
        - dupl
    # Allow specific gosec rules in main files for necessary operations
    - linters:
        - gosec
      text: "G304.*file inclusion via variable"
    - linters:
        - gosec
      text: "G204.*subprocess launched with variable"