before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: mcp-hub
    main: ./main.go
    binary: mcp-hub
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: binaries
    builds:
      - mcp-hub
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

nfpms:
  - id: packages
    package_name: mcp-hub
    vendor: MCP Hub
    homepage: https://github.com/gabadi/cc-mcp-manager
    maintainer: Gabriel Adomnicai <gabadi@users.noreply.github.com>
    description: TUI for managing Claude MCP configurations
    license: MIT
    formats:
      - deb
      - rpm

release:
  github:
    owner: gabadi
    name: cc-mcp-manager
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"

# NPM package will be created manually using GitHub Actions script

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'