before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: mcp-hub
    main: ./main.go
    binary: mcp-hub
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: binaries
    builds:
      - mcp-hub
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

nfpms:
  - id: packages
    package_name: mcp-hub
    vendor: MCP Hub
    homepage: https://github.com/gabadi/cc-mcp-manager
    maintainer: Gabriel Adomnicai <gabadi@users.noreply.github.com>
    description: TUI for managing Claude MCP configurations
    license: MIT
    formats:
      - deb
      - rpm

release:
  github:
    owner: gabadi
    name: cc-mcp-manager
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"

# Custom NPM package creation using after hooks
after:
  hooks:
    - mkdir -p dist/npm-package/bin
    - cp index.js dist/npm-package/
    - cp package.json dist/npm-package/
    - cp README.md dist/npm-package/
    - cp LICENSE dist/npm-package/
    - cp dist/mcp-hub_linux_amd64_v1/mcp-hub dist/npm-package/bin/mcp-hub-linux-amd64
    - cp dist/mcp-hub_linux_arm64/mcp-hub dist/npm-package/bin/mcp-hub-linux-arm64
    - cp dist/mcp-hub_darwin_amd64_v1/mcp-hub dist/npm-package/bin/mcp-hub-darwin-amd64
    - cp dist/mcp-hub_darwin_arm64/mcp-hub dist/npm-package/bin/mcp-hub-darwin-arm64
    - cp dist/mcp-hub_windows_amd64_v1/mcp-hub.exe dist/npm-package/bin/mcp-hub-windows-amd64.exe
    - cp dist/mcp-hub_windows_arm64/mcp-hub.exe dist/npm-package/bin/mcp-hub-windows-arm64.exe
    - cd dist/npm-package && npm publish

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'